name: ccandl_media
description: "The new multi media platform only for code."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  permission_handler: ^11.3.1
  anim_search_bar: ^2.0.3
  url_launcher: ^6.2.6
  camera: ^0.10.5+9
  file_picker: ^8.0.1
  # file_picker_web: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/img/

  uses-material-design: true
